### PR TITLE
Add Web Demo with A100 support & Docker environment 

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @Sleepychord 👋 

We’ve seen that people are as exited about the release of the model as we are, and wanted to test CogView2 but often are unable to due to the GPU constraint - we implemented a web demo hosted on Replicate, which is backed by a big auto-scaling cluster of A100s, view it here: https://replicate.com/thudm/cogview2

Screenshot 2022-06-17 at 11 00 05

This pull request includes the configuration for [Cog](https://github.com/replicate/cog), a tool for packaging models in a standard format. Replicate uses this format to run the model.

We have added some examples in the [gallery](https://replicate.com/thudm/cogview2/examples) here, but do [Claim your page here](https://replicate.com/thudm/cogview2/claim) so you can edit it, and we'll feature it on our website and tweet about it too.

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by Sleepychord** [comment]
Thank you for your work! It is amazing to see that you deploy it on Replicate!

**Comment by chenxwh** [comment]
> Thank you for your work! It is amazing to see that you deploy it on Replicate!

@Sleepychord We are glad to hear you like the demo, we'd appreciate if you could kindly claim the page here https://replicate.com/thudm/cogview2/claim, then we can make the demo public on our website and enable API for it too!

Cheers!

**Comment by Sleepychord** [comment]
Hi @chenxwh , It is probably much slower for the first time to run,  due to the loading the models and cache reasons. Will your pipeline avoid this? Also, you can tell the user in the issues about the demo~

**Comment by chenxwh** [comment]
Great! 

It still takes longer the first time to run due to allocating a GPU, prepare the `setup()` (in `predict.py`). But the weights pre-downloaded and included in the docker image, so there won't be downloading model overhead even if it is the first time. I separated the model loading and `style` assigning steps, so later inferences (where only `predict()` will run) with different style won't need to re-load the model which makes the inference faster.

**Pull request merged**
